feat: build.yml: run local file at time of build

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -9,7 +9,15 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
+    uses: [actions/checkout@v3, ./.github/actions/prepare]
     steps:
-      - uses: actions/checkout@v3
-      - uses: ./.github/actions/prepare
-      - run: pnpm build
+      - id: test1
+        run: |
+          pnpm build | sed 's/^/ Build Test : '
+      - id: test2
+        run: |
+          if node ./src/index.ts ; then
+              echo $? | sed 's/^/Imports Test : success : '
+          else
+              echo $? | sed 's/^/Imports Test : failed : '
+          fi
